/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-users': CmsUserAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-users': CmsUser;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cms-users': CmsUsersSelect<false> | CmsUsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'landing-content': LandingContent;
  };
  globalsSelect: {
    'landing-content': LandingContentSelect<false> | LandingContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: CmsUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users".
 */
export interface CmsUser {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cms-users';
        value: number | CmsUser;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms-users';
    value: number | CmsUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-users_select".
 */
export interface CmsUsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-content".
 */
export interface LandingContent {
  id: number;
  meta: {
    title: string;
    /**
     * Leans into the PH-POS framing to separate us from sentry.io in search results.
     */
    description: string;
  };
  /**
   * One page, no menu — these jump to section anchors. Use #counter, #numbers, #branches, #product or #contact.
   */
  nav?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  hero: {
    /**
     * The small pill above the headline. Keep it short and true.
     */
    badge: string;
    headline: string;
    sub: string;
    primaryCta: string;
    secondaryCta: string;
    /**
     * Scrolls under the hero. Sample events, written the way the activity log writes them.
     */
    ticker?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  features?:
    | {
        icon: 'counter' | 'chart' | 'record';
        tone: 'mint' | 'purple' | 'orange';
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The band beside the POS mockup.
   */
  counter: {
    eyebrow: string;
    heading: string;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The band beside the tax-summary mockup.
   */
  numbers: {
    eyebrow: string;
    heading: string;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  branches: {
    heading: string;
    /**
     * Each card pairs one line of copy with a fixed illustration. Pick which illustration sits above the line.
     */
    cards?:
      | {
          mockup: 'transfer' | 'expiry' | 'stocktake' | 'terminals';
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * The dark showcase card and the grid of smaller claims below it.
   */
  product: {
    eyebrow: string;
    heading: string;
    sub: string;
    /**
     * Left to right, under the three device mockups.
     */
    captions?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  extras: {
    heading: string;
    cards?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  banner: {
    line: string;
    cta: string;
  };
  contact: {
    /**
     * Backs every Request access button as well as the two contact rows.
     */
    email: string;
    websiteUrl: string;
    websiteLabel: string;
    facebookUrl: string;
    facebookLabel: string;
  };
  footer: {
    links?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    copyright: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-content_select".
 */
export interface LandingContentSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  nav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        badge?: T;
        headline?: T;
        sub?: T;
        primaryCta?: T;
        secondaryCta?: T;
        ticker?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  features?:
    | T
    | {
        icon?: T;
        tone?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  counter?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  numbers?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  branches?:
    | T
    | {
        heading?: T;
        cards?:
          | T
          | {
              mockup?: T;
              text?: T;
              id?: T;
            };
      };
  product?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        sub?: T;
        captions?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  extras?:
    | T
    | {
        heading?: T;
        cards?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  banner?:
    | T
    | {
        line?: T;
        cta?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        websiteUrl?: T;
        websiteLabel?: T;
        facebookUrl?: T;
        facebookLabel?: T;
      };
  footer?:
    | T
    | {
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        copyright?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}